/// Generated by AssetsRefGenerator on 2022/01/11
class Res {
  static const String logo = "assets/logo.png";
  static const String logo2 = "assets/logo2.png";
  static const String logo3 = "assets/logo3.png";
  static const String logo4 = "assets/logo4.png";
  static const String logo5 = "assets/logo5.PNG";
  static const String logo6 = "assets/logo6.PNG";
  static const String logo7 = "assets/logo7.PNG";
  static const String logocarbo = "assets/logocarbo.png";
  static const String logowhatsapp = "assets/logowhatsapp.png";
}
